create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

create policy "Anyone can send contact messages"
on public.contact_messages
for insert
to anon
with check (
  char_length(name) between 1 and 100
  and char_length(email) between 3 and 200
  and char_length(message) between 1 and 5000
);
